[package]
name = "simple_server"
version = "0.1.0"
authors = ["Colin Moore <colin@moore.one>"]
edition = "2018"

[dependencies]
env_logger = "0.8.1"
actix-web = "3.3.2"
phalanx = { path = "../../phalanx" }
